### ISSUE TITLE
Prerequisite Engineering  for Roadbuild and Minning

### ISSUE THREAD

**Issue by Deadly-Insect** [tsjensen/civbuddy#9]
Hello,

In the code of the page:
/src/ts/rules/advanced.json

At line 128 and line 155:
Instead of "prereq": 6, it should be written as "prereq": "Engineering",.

This way, the two cards, Roadbuild and Mining, would require Engineering as a prerequisite, whereas currently it's not the case, even though the game requires having the card to purchase the other two.

Thank you.
Have a nice day.

**Comment by tsjensen** [comment]
Thank you for telling us, @Deadly-Insect!

That's a bug for sure. Do you want to submit a pull request for it?  
If not, I will do it (you described the fix very precisely).

Either way, I hope to get a release out within the next couple of weeks. (Currently traveling.)

**Comment by Deadly-Insect** [comment]
Hello,

I have submitted the pull request.
Thank you.

Have a great vacation.

**Comment by tsjensen** [comment]
Released as [v2.3.6](https://github.com/tsjensen/civbuddy/releases/tag/v2.3.6)! 🎉

Remember to press "Refresh" in your browser to get the latest version of CivBuddy.

**Comment by Deadly-Insect** [comment]
Wonderful!!!!!!
